language:
  - node_js

node_js:
  - node

cache: npm

script:
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - npm ci
  - echo 'Testing!'
  - npm run test:coverage

after_script:
  - COVERALLS_REPO_TOKEN=tiwzMgpOeg9d3piiQYRN4uohsRMUx99wd npm run test:coveralls

notifications:
  email: false
