sudo: false

language:
  - node_js
  - "lts/*"

script:
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - npm ci
  - echo 'Testing!'
  - npm run test

install:
  - npm ci

notifications:
  email: true
