language:
  - node_js

node_js:
  - node

cache: npm

script:
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - npm ci
  - echo 'Testing!'
  - npm run test:coverage

notifications:
  email: false
